name: BlueEra
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 13.40.20+75

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.1.0
  octo_image: ^2.1.0
  shimmer: ^3.0.0
  flutter_secure_storage: ^9.2.4
  dio: ^5.8.0+1
  get: ^4.7.2
  flutter_localization: ^0.3.1
  sms_autofill: ^2.4.1
  pinput: ^5.0.1
  image_picker: ^1.2.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.1
  camera: ^0.10.5+9
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  croppy: ^1.3.6
  encrypt: ^5.0.3
  path: ^1.9.0
  #chewie: ^1.13.0
  readmore: ^3.0.0
  visibility_detector: ^0.4.0+2
  # MAP
#  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  internet_connection_checker_plus: ^2.7.2
  flutter_contacts: ^1.1.9+2
  audioplayers: ^6.5.0
  audio_waveforms: ^1.3.0
  fvm: ^3.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  socket_io_client: ^3.1.2
  dotted_border: 2.1.0
  onesignal_flutter: ^5.3.4
  mime: ^2.0.0
  #cached_video_player_plus: ^4.0.3
  video_player: ^2.10.0
  #flutter_image_slideshow: ^0.1.5
  file_picker: ^10.2.0
  just_audio: ^0.10.4
  rxdart: ^0.28.0
  flutter_pdfview: ^1.4.1+1
  pdfx: ^2.9.2
  emoji_picker_flutter: ^4.3.0
  flutter_sound: ^9.28.0
  timeago: ^3.7.1
  razorpay_flutter: ^1.4.0
  connectivity_plus: ^6.1.4
  webview_flutter: ^4.13.0
  open_file: ^3.5.10
  package_info_plus: ^8.3.0
  video_thumbnail: ^0.5.3
  mappls_gl: ^1.2.0
  share_plus: ^11.1.0
  app_links: ^6.4.1
  google_mobile_ads: ^5.3.1
  workmanager: ^0.7.0
  video_compress: ^3.1.4
  loading_animation_widget: ^1.3.0
  flutter_rating_bar: ^4.0.1
  flutter_upgrade_version: ^1.1.8
  flutter_image_compress: ^2.4.0
  any_link_preview: ^3.0.3
  pro_image_editor: ^11.3.0
  carousel_slider: ^5.1.1
  image: ^4.5.4
  rating_summary: ^1.0.4
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.2

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/jsons/
    - assets/icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Arizonia
      fonts:
        - asset: assets/fonts/Arizonia.ttf
    - family: Artifika
      fonts:
        - asset: assets/fonts/Artifika.ttf
    - family: AsapCondensed
      fonts:
        - asset: assets/fonts/AsapCondensed.ttf



