import 'dart:developer';
import 'dart:ui' as ui;

import 'package:BlueEra/core/constants/getx_utils.dart';
import 'package:BlueEra/core/constants/shared_preference_utils.dart';
import 'package:BlueEra/features/chat/auth/controller/payment_qr_controller.dart';
import 'package:BlueEra/features/chat/auth/controller/upi_payment_controller.dart';
import 'package:http/http.dart' as http;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:qr_flutter/qr_flutter.dart';

/// The shop owner's payment scanner, rendered for embedding in a packing PDF.
class PackingPaymentQr {
  const PackingPaymentQr({
    required this.image,
    this.upiId,
    this.mobileNumber,
  });

  /// The scanner as a PNG, ready for [pw.Image].
  final pw.MemoryImage image;

  /// The payee VPA, printed under the QR so the customer can pay manually if
  /// the scan fails.
  final String? upiId;

  /// The payee's linked mobile number, when one is known.
  final String? mobileNumber;
}

/// Builds the packing-PDF payment scanner for the shop owner.
///
/// Prefers the scanner the owner has **already registered** through their
/// "My Payment QR" sheet ([PaymentQrController.primaryQr]) — that is the real
/// QR image they uploaded from their UPI app, so the packing slip carries the
/// exact scanner they hand customers over the counter.
///
/// Falls back to generating a standard `upi://pay` QR from the UPI id on
/// `wallet-service/wallet/user/{userId}/upi` — the same payload the chat's
/// payment sheet renders — for owners who never registered an image.
///
/// [ownerUserId] defaults to the logged-in user because the packing slip is
/// always generated by the shop: the money flows *to* whoever is packing the
/// order, not to the conversation person.
///
/// Returns null (and never throws) when neither source yields a scanner, so
/// PDF generation degrades to the old QR-less layout instead of failing.
Future<PackingPaymentQr?> buildShopOwnerPaymentQr({
  required String payeeName,
  String? orderId,
  String? ownerUserId,
}) async {
  final registered = await _registeredScanner();
  if (registered != null) return registered;

  return _generatedUpiScanner(
    payeeName: payeeName,
    orderId: orderId,
    ownerUserId: ownerUserId,
  );
}

/// The QR image the owner uploaded via the "My Payment QR" sheet.
Future<PackingPaymentQr?> _registeredScanner() async {
  try {
    final controller = getOrPut(() => PaymentQrController());
    if (controller.myQrs.isEmpty) {
      await controller.loadMyQrs();
    }

    final qr = controller.primaryQr;
    final imageUrl = qr?.qrImageUrl ?? '';
    if (qr == null || imageUrl.isEmpty) return null;

    final response = await http.get(Uri.parse(imageUrl));
    if (response.statusCode != 200) {
      log('packing QR: registered scanner fetch failed '
          '(${response.statusCode})');
      return null;
    }

    return PackingPaymentQr(
      image: pw.MemoryImage(response.bodyBytes),
      upiId: qr.upiId,
      mobileNumber: qr.upiPhoneNumber,
    );
  } catch (e) {
    log('packing QR: registered scanner unavailable: $e');
    return null;
  }
}

/// A standard `upi://pay` QR drawn from the owner's wallet UPI id.
Future<PackingPaymentQr?> _generatedUpiScanner({
  required String payeeName,
  String? orderId,
  String? ownerUserId,
}) async {
  final id = (ownerUserId ?? '').isNotEmpty ? ownerUserId! : userId;
  if (id.isEmpty) {
    log('packing QR: no shop owner id, skipping QR');
    return null;
  }

  try {
    final upiController = UpiPaymentController();
    await upiController.fetchUserUpi(id);

    final vpa = upiController.upiId.value;
    if (vpa == null || vpa.isEmpty) {
      log('packing QR: no UPI id for $id, skipping QR');
      return null;
    }

    // Amount is intentionally omitted so the scanning app asks the payer for
    // it — same choice as the in-chat payment sheet.
    final payload = Uri.parse('upi://pay').replace(queryParameters: {
      'pa': vpa,
      'pn': payeeName,
      'cu': 'INR',
      if ((orderId ?? '').isNotEmpty) 'tn': 'Order $orderId',
    }).toString();

    final painter = QrPainter(
      data: payload,
      version: QrVersions.auto,
      gapless: true,
      errorCorrectionLevel: QrErrorCorrectLevel.H,
    );

    // 600px keeps the code crisp at the ~110pt it is printed at.
    final bytes =
        await painter.toImageData(600, format: ui.ImageByteFormat.png);
    if (bytes == null) return null;

    return PackingPaymentQr(
      image: pw.MemoryImage(bytes.buffer.asUint8List()),
      upiId: vpa,
      mobileNumber: upiController.mobileNumber.value,
    );
  } catch (e) {
    log('packing QR: failed to build QR: $e');
    return null;
  }
}

/// The "Scan & Pay" block appended to the end of a packing PDF.
pw.Widget buildPackingPaymentQrSection(PackingPaymentQr qr) {
  final labelStyle = pw.TextStyle(
    fontSize: 9,
    color: PdfColor.fromHex('#757575'),
  );

  return pw.Container(
    width: double.infinity,
    padding: const pw.EdgeInsets.all(12),
    decoration: pw.BoxDecoration(
      borderRadius: pw.BorderRadius.circular(8),
      border: pw.Border.all(color: PdfColors.grey300, width: 0.5),
    ),
    child: pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.center,
      children: [
        pw.Container(
          width: 110,
          height: 110,
          padding: const pw.EdgeInsets.all(6),
          decoration: pw.BoxDecoration(
            color: PdfColors.white,
            borderRadius: pw.BorderRadius.circular(6),
            border: pw.Border.all(color: PdfColors.grey300, width: 0.5),
          ),
          child: pw.Image(qr.image, fit: pw.BoxFit.contain),
        ),
        pw.SizedBox(width: 14),
        pw.Expanded(
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'Scan & Pay',
                style: pw.TextStyle(
                  fontSize: 14,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColor.fromHex('#1565C0'),
                ),
              ),
              pw.SizedBox(height: 3),
              pw.Text(
                'Scan this QR with any UPI app to pay for this order.',
                style: labelStyle,
              ),
              if ((qr.upiId ?? '').isNotEmpty) ...[
                pw.SizedBox(height: 8),
                pw.Text('UPI ID', style: labelStyle),
                pw.Text(
                  qr.upiId!,
                  style: pw.TextStyle(
                    fontSize: 11,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ],
              if ((qr.mobileNumber ?? '').isNotEmpty) ...[
                pw.SizedBox(height: 6),
                pw.Text('Mobile', style: labelStyle),
                pw.Text(
                  qr.mobileNumber!,
                  style: pw.TextStyle(
                    fontSize: 11,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ],
            ],
          ),
        ),
      ],
    ),
  );
}
