#!/usr/bin/env python3
"""Localization for the standalone-doctor module (lib/features/me/doctor/).

  * NEW      — every label, hint, empty state and validation message the
               Booking / Overview / About Me / Statics tabs and the
               certificates screen introduce.
  * BACKFILL — `read_less` and `retry`, which had only shipped in en+hi;
               existing values reused verbatim.

Run:  python3 scripts/doctor_module_localization.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TRANS_DIR = os.path.join(ROOT, "assets", "translations")
OUT_DIR = os.path.join(ROOT, "scripts", "doctor_module_lang_payloads")

T = {
    "en": {
        "doctorBooking": "Booking",
        "doctorAboutMe": "About Me",
        "doctorAboutTab": "About",
        "doctorStatics": "Statics",
        "doctorCoverPhoto": "Cover Photo",
        "doctorAddCoverPhoto": "Add a cover photo",
        "doctorExpertise": "Expertise",
        "doctorExpertiseHint": "E.g. Angioplasty",
        "doctorAddExpertise": "Add your expertise",
        "doctorCertificateAwards": "Certificate & Awards",
        "doctorAddCertificate": "Add Certificate",
        "doctorEditCertificate": "Edit Certificate",
        "doctorNoCertificates": "Add your first certificate",
        "doctorCertificateImage": "Certificate Image",
        "doctorCertificateTitleHint": "E.g. Membership Certificate",
        "doctorCertificateDescHint": "Describe this certificate...",
        "doctorCertificateTitleRequired": "Please enter a certificate title",
        "doctorCertificateTitleLimit":
            "Title cannot exceed 200 characters",
        "doctorIssuedBy": "Issued By",
        "doctorIssuedByHint": "E.g. Medical Council of India",
        "doctorIssuedDate": "Issued Date",
        "doctorSelectDate": "Select date",
        "doctorImageTooLarge": "Image must be 10 MB or smaller",
        "doctorAddPhoto": "Add Photo",
        "doctorGalleryEmpty": "Your gallery is empty - add photos to showcase",
        "doctorDegree": "Degree",
        "doctorDegreeHint": "E.g. MBBS",
        "doctorSpecialization": "Specialization",
        "doctorSpecializationHint": "E.g. Cardiologist (Heart)",
        "doctorLanguageSpoken": "Language Spoken",
        "doctorLanguageHint": "E.g. English",
        "doctorLanguagesSpoken": "Languages Spoken",
        "doctorExperience": "Experience",
        "doctorExperienceHint": "E.g. 10 Years",
        "doctorYears": "Years",
        "doctorRegistrationNumber": "Registration Number",
        "doctorRegistrationHint": "E.g. 2345/MC/2015",
        "doctorConsultationFee": "Consultation Fee",
        "doctorFeeHint": "E.g. 600",
        "doctorAddressHint": "E.g. 123 Park Street, Kolkata",
        "doctorDescriptionHint": "Tell patients about yourself...",
        "doctorConsultationAvailability": "Consultation Availability",
        "doctorAddVisitingDays": "Add Your Visiting Days",
        "doctorCompleteProfileTitle": "Complete your profile",
        "doctorCompleteProfileBody":
            "Add your degree, specialization and fee so patients can find and book you.",
        "doctorCreateProfile": "Create Profile",
        "doctorMaxEntriesError": "You can add up to 30 entries per field",
        "doctorExperienceRangeError":
            "Experience must be between 0 and 80 years",
        "doctorFeeError": "Consultation fee must be 0 or more",
        "doctorDescriptionLimitError":
            "Description cannot exceed 1000 characters",
        "doctorNoAppointments": "No appointment requests yet",
        "doctorLoadMore": "Load More",
        "doctorFilterAll": "All",
        "doctorStatusPending": "Pending",
        "doctorStatusAccepted": "Accepted",
        "doctorStatusDeclined": "Declined",
        "doctorStatusCancelled": "Cancelled",
        "doctorAccept": "Accept",
        "doctorDecline": "Decline",
        "doctorPatient": "Patient",
        "doctorAttachments": "attachments",
        "doctorAppointmentStats": "Appointments",
        "doctorTotalRequests": "Total Requests",
        "doctorUpcomingVisits": "Upcoming Visits",
        "doctorCertificates": "Certificates",
        # --- backfill (existing en values) ---
        "read_less": "Read Less",
        "retry": "Retry",
    },
    "hi": {
        "doctorBooking": "बुकिंग",
        "doctorAboutMe": "मेरे बारे में",
        "doctorAboutTab": "बारे में",
        "doctorStatics": "आंकड़े",
        "doctorCoverPhoto": "कवर फ़ोटो",
        "doctorAddCoverPhoto": "एक कवर फ़ोटो जोड़ें",
        "doctorExpertise": "विशेषज्ञता",
        "doctorExpertiseHint": "उदा. एंजियोप्लास्टी",
        "doctorAddExpertise": "अपनी विशेषज्ञता जोड़ें",
        "doctorCertificateAwards": "प्रमाणपत्र और पुरस्कार",
        "doctorAddCertificate": "प्रमाणपत्र जोड़ें",
        "doctorEditCertificate": "प्रमाणपत्र संपादित करें",
        "doctorNoCertificates": "अपना पहला प्रमाणपत्र जोड़ें",
        "doctorCertificateImage": "प्रमाणपत्र छवि",
        "doctorCertificateTitleHint": "उदा. सदस्यता प्रमाणपत्र",
        "doctorCertificateDescHint": "इस प्रमाणपत्र का वर्णन करें...",
        "doctorCertificateTitleRequired":
            "कृपया प्रमाणपत्र का शीर्षक दर्ज करें",
        "doctorCertificateTitleLimit":
            "शीर्षक 200 अक्षरों से अधिक नहीं हो सकता",
        "doctorIssuedBy": "जारीकर्ता",
        "doctorIssuedByHint": "उदा. भारतीय चिकित्सा परिषद",
        "doctorIssuedDate": "जारी करने की तिथि",
        "doctorSelectDate": "तिथि चुनें",
        "doctorImageTooLarge": "छवि 10 MB या उससे कम होनी चाहिए",
        "doctorAddPhoto": "फ़ोटो जोड़ें",
        "doctorGalleryEmpty":
            "आपकी गैलरी खाली है - प्रदर्शित करने के लिए फ़ोटो जोड़ें",
        "doctorDegree": "डिग्री",
        "doctorDegreeHint": "उदा. एमबीबीएस",
        "doctorSpecialization": "विशेषज्ञता क्षेत्र",
        "doctorSpecializationHint": "उदा. हृदय रोग विशेषज्ञ",
        "doctorLanguageSpoken": "बोली जाने वाली भाषा",
        "doctorLanguageHint": "उदा. अंग्रेज़ी",
        "doctorLanguagesSpoken": "बोली जाने वाली भाषाएं",
        "doctorExperience": "अनुभव",
        "doctorExperienceHint": "उदा. 10 वर्ष",
        "doctorYears": "वर्ष",
        "doctorRegistrationNumber": "पंजीकरण संख्या",
        "doctorRegistrationHint": "उदा. 2345/MC/2015",
        "doctorConsultationFee": "परामर्श शुल्क",
        "doctorFeeHint": "उदा. 600",
        "doctorAddressHint": "उदा. 123 पार्क स्ट्रीट, कोलकाता",
        "doctorDescriptionHint": "मरीजों को अपने बारे में बताएं...",
        "doctorConsultationAvailability": "परामर्श उपलब्धता",
        "doctorAddVisitingDays": "अपने विज़िटिंग दिन जोड़ें",
        "doctorCompleteProfileTitle": "अपनी प्रोफ़ाइल पूरी करें",
        "doctorCompleteProfileBody":
            "अपनी डिग्री, विशेषज्ञता और शुल्क जोड़ें ताकि मरीज़ आपको ढूंढ और बुक कर सकें।",
        "doctorCreateProfile": "प्रोफ़ाइल बनाएं",
        "doctorMaxEntriesError":
            "आप प्रति फ़ील्ड अधिकतम 30 प्रविष्टियां जोड़ सकते हैं",
        "doctorExperienceRangeError":
            "अनुभव 0 से 80 वर्ष के बीच होना चाहिए",
        "doctorFeeError": "परामर्श शुल्क 0 या अधिक होना चाहिए",
        "doctorDescriptionLimitError":
            "विवरण 1000 अक्षरों से अधिक नहीं हो सकता",
        "doctorNoAppointments": "अभी तक कोई अपॉइंटमेंट अनुरोध नहीं",
        "doctorLoadMore": "और लोड करें",
        "doctorFilterAll": "सभी",
        "doctorStatusPending": "लंबित",
        "doctorStatusAccepted": "स्वीकृत",
        "doctorStatusDeclined": "अस्वीकृत",
        "doctorStatusCancelled": "रद्द",
        "doctorAccept": "स्वीकार करें",
        "doctorDecline": "अस्वीकार करें",
        "doctorPatient": "मरीज़",
        "doctorAttachments": "अटैचमेंट",
        "doctorAppointmentStats": "अपॉइंटमेंट",
        "doctorTotalRequests": "कुल अनुरोध",
        "doctorUpcomingVisits": "आगामी विज़िट",
        "doctorCertificates": "प्रमाणपत्र",
        "read_less": "कम पढ़ें",
        "retry": "पुनः प्रयास करें",
    },
    "gu": {
        "doctorBooking": "બુકિંગ",
        "doctorAboutMe": "મારા વિશે",
        "doctorAboutTab": "વિશે",
        "doctorStatics": "આંકડા",
        "doctorCoverPhoto": "કવર ફોટો",
        "doctorAddCoverPhoto": "કવર ફોટો ઉમેરો",
        "doctorExpertise": "નિપુણતા",
        "doctorExpertiseHint": "દા.ત. એન્જિયોપ્લાસ્ટી",
        "doctorAddExpertise": "તમારી નિપુણતા ઉમેરો",
        "doctorCertificateAwards": "પ્રમાણપત્રો અને પુરસ્કારો",
        "doctorAddCertificate": "પ્રમાણપત્ર ઉમેરો",
        "doctorEditCertificate": "પ્રમાણપત્ર સંપાદિત કરો",
        "doctorNoCertificates": "તમારું પ્રથમ પ્રમાણપત્ર ઉમેરો",
        "doctorCertificateImage": "પ્રમાણપત્ર છબી",
        "doctorCertificateTitleHint": "દા.ત. સભ્યપદ પ્રમાણપત્ર",
        "doctorCertificateDescHint": "આ પ્રમાણપત્રનું વર્ણન કરો...",
        "doctorCertificateTitleRequired":
            "કૃપા કરીને પ્રમાણપત્રનું શીર્ષક દાખલ કરો",
        "doctorCertificateTitleLimit":
            "શીર્ષક 200 અક્ષરોથી વધુ ન હોઈ શકે",
        "doctorIssuedBy": "જારીકર્તા",
        "doctorIssuedByHint": "દા.ત. મેડિકલ કાઉન્સિલ ઓફ ઈન્ડિયા",
        "doctorIssuedDate": "જારી તારીખ",
        "doctorSelectDate": "તારીખ પસંદ કરો",
        "doctorImageTooLarge": "છબી 10 MB કે તેથી ઓછી હોવી જોઈએ",
        "doctorAddPhoto": "ફોટો ઉમેરો",
        "doctorGalleryEmpty":
            "તમારી ગેલેરી ખાલી છે - પ્રદર્શિત કરવા માટે ફોટા ઉમેરો",
        "doctorDegree": "ડિગ્રી",
        "doctorDegreeHint": "દા.ત. એમબીબીએસ",
        "doctorSpecialization": "વિશેષતા",
        "doctorSpecializationHint": "દા.ત. હૃદયરોગ નિષ્ણાત",
        "doctorLanguageSpoken": "બોલાતી ભાષા",
        "doctorLanguageHint": "દા.ત. અંગ્રેજી",
        "doctorLanguagesSpoken": "બોલાતી ભાષાઓ",
        "doctorExperience": "અનુભવ",
        "doctorExperienceHint": "દા.ત. 10 વર્ષ",
        "doctorYears": "વર્ષ",
        "doctorRegistrationNumber": "નોંધણી નંબર",
        "doctorRegistrationHint": "દા.ત. 2345/MC/2015",
        "doctorConsultationFee": "પરામર્શ ફી",
        "doctorFeeHint": "દા.ત. 600",
        "doctorAddressHint": "દા.ત. 123 પાર્ક સ્ટ્રીટ, કોલકાતા",
        "doctorDescriptionHint": "દર્દીઓને તમારા વિશે જણાવો...",
        "doctorConsultationAvailability": "પરામર્શ ઉપલબ્ધતા",
        "doctorAddVisitingDays": "તમારા વિઝિટિંગ દિવસો ઉમેરો",
        "doctorCompleteProfileTitle": "તમારી પ્રોફાઇલ પૂર્ણ કરો",
        "doctorCompleteProfileBody":
            "તમારી ડિગ્રી, વિશેષતા અને ફી ઉમેરો જેથી દર્દીઓ તમને શોધી અને બુક કરી શકે.",
        "doctorCreateProfile": "પ્રોફાઇલ બનાવો",
        "doctorMaxEntriesError":
            "તમે ફીલ્ડ દીઠ વધુમાં વધુ 30 એન્ટ્રીઓ ઉમેરી શકો છો",
        "doctorExperienceRangeError":
            "અનુભવ 0 થી 80 વર્ષની વચ્ચે હોવો જોઈએ",
        "doctorFeeError": "પરામર્શ ફી 0 કે તેથી વધુ હોવી જોઈએ",
        "doctorDescriptionLimitError":
            "વર્ણન 1000 અક્ષરોથી વધુ ન હોઈ શકે",
        "doctorNoAppointments": "હજી સુધી કોઈ એપોઇન્ટમેન્ટ વિનંતી નથી",
        "doctorLoadMore": "વધુ લોડ કરો",
        "doctorFilterAll": "બધા",
        "doctorStatusPending": "બાકી",
        "doctorStatusAccepted": "સ્વીકૃત",
        "doctorStatusDeclined": "નકારેલ",
        "doctorStatusCancelled": "રદ",
        "doctorAccept": "સ્વીકારો",
        "doctorDecline": "નકારો",
        "doctorPatient": "દર્દી",
        "doctorAttachments": "જોડાણો",
        "doctorAppointmentStats": "એપોઇન્ટમેન્ટ",
        "doctorTotalRequests": "કુલ વિનંતીઓ",
        "doctorUpcomingVisits": "આગામી મુલાકાતો",
        "doctorCertificates": "પ્રમાણપત્રો",
        "read_less": "ઓછું વાંચો",
        "retry": "ફરી પ્રયાસ કરો",
    },
    "mr": {
        "doctorBooking": "बुकिंग",
        "doctorAboutMe": "माझ्याबद्दल",
        "doctorAboutTab": "बद्दल",
        "doctorStatics": "आकडेवारी",
        "doctorCoverPhoto": "कव्हर फोटो",
        "doctorAddCoverPhoto": "कव्हर फोटो जोडा",
        "doctorExpertise": "कौशल्य",
        "doctorExpertiseHint": "उदा. अँजिओप्लास्टी",
        "doctorAddExpertise": "तुमचे कौशल्य जोडा",
        "doctorCertificateAwards": "प्रमाणपत्रे आणि पुरस्कार",
        "doctorAddCertificate": "प्रमाणपत्र जोडा",
        "doctorEditCertificate": "प्रमाणपत्र संपादित करा",
        "doctorNoCertificates": "तुमचे पहिले प्रमाणपत्र जोडा",
        "doctorCertificateImage": "प्रमाणपत्र प्रतिमा",
        "doctorCertificateTitleHint": "उदा. सदस्यत्व प्रमाणपत्र",
        "doctorCertificateDescHint": "या प्रमाणपत्राचे वर्णन करा...",
        "doctorCertificateTitleRequired":
            "कृपया प्रमाणपत्राचे शीर्षक प्रविष्ट करा",
        "doctorCertificateTitleLimit":
            "शीर्षक 200 अक्षरांपेक्षा जास्त असू शकत नाही",
        "doctorIssuedBy": "जारीकर्ता",
        "doctorIssuedByHint": "उदा. मेडिकल कौन्सिल ऑफ इंडिया",
        "doctorIssuedDate": "जारी तारीख",
        "doctorSelectDate": "तारीख निवडा",
        "doctorImageTooLarge": "प्रतिमा 10 MB किंवा त्यापेक्षा कमी असावी",
        "doctorAddPhoto": "फोटो जोडा",
        "doctorGalleryEmpty":
            "तुमची गॅलरी रिकामी आहे - प्रदर्शित करण्यासाठी फोटो जोडा",
        "doctorDegree": "पदवी",
        "doctorDegreeHint": "उदा. एमबीबीएस",
        "doctorSpecialization": "विशेषज्ञता",
        "doctorSpecializationHint": "उदा. हृदयरोग तज्ञ",
        "doctorLanguageSpoken": "बोलली जाणारी भाषा",
        "doctorLanguageHint": "उदा. इंग्रजी",
        "doctorLanguagesSpoken": "बोलल्या जाणाऱ्या भाषा",
        "doctorExperience": "अनुभव",
        "doctorExperienceHint": "उदा. 10 वर्षे",
        "doctorYears": "वर्षे",
        "doctorRegistrationNumber": "नोंदणी क्रमांक",
        "doctorRegistrationHint": "उदा. 2345/MC/2015",
        "doctorConsultationFee": "सल्ला शुल्क",
        "doctorFeeHint": "उदा. 600",
        "doctorAddressHint": "उदा. 123 पार्क स्ट्रीट, कोलकाता",
        "doctorDescriptionHint": "रुग्णांना तुमच्याबद्दल सांगा...",
        "doctorConsultationAvailability": "सल्ला उपलब्धता",
        "doctorAddVisitingDays": "तुमचे भेटीचे दिवस जोडा",
        "doctorCompleteProfileTitle": "तुमची प्रोफाइल पूर्ण करा",
        "doctorCompleteProfileBody":
            "तुमची पदवी, विशेषज्ञता आणि शुल्क जोडा जेणेकरून रुग्ण तुम्हाला शोधू आणि बुक करू शकतील.",
        "doctorCreateProfile": "प्रोफाइल तयार करा",
        "doctorMaxEntriesError":
            "तुम्ही प्रति फील्ड जास्तीत जास्त 30 नोंदी जोडू शकता",
        "doctorExperienceRangeError":
            "अनुभव 0 ते 80 वर्षांदरम्यान असावा",
        "doctorFeeError": "सल्ला शुल्क 0 किंवा अधिक असावे",
        "doctorDescriptionLimitError":
            "वर्णन 1000 अक्षरांपेक्षा जास्त असू शकत नाही",
        "doctorNoAppointments": "अद्याप कोणतीही अपॉइंटमेंट विनंती नाही",
        "doctorLoadMore": "अधिक लोड करा",
        "doctorFilterAll": "सर्व",
        "doctorStatusPending": "प्रलंबित",
        "doctorStatusAccepted": "स्वीकारले",
        "doctorStatusDeclined": "नाकारले",
        "doctorStatusCancelled": "रद्द",
        "doctorAccept": "स्वीकारा",
        "doctorDecline": "नाकारा",
        "doctorPatient": "रुग्ण",
        "doctorAttachments": "संलग्नके",
        "doctorAppointmentStats": "अपॉइंटमेंट",
        "doctorTotalRequests": "एकूण विनंत्या",
        "doctorUpcomingVisits": "आगामी भेटी",
        "doctorCertificates": "प्रमाणपत्रे",
        "read_less": "कमी वाचा",
        "retry": "पुन्हा प्रयत्न करा",
    },
    "kn": {
        "doctorBooking": "ಬುಕಿಂಗ್",
        "doctorAboutMe": "ನನ್ನ ಬಗ್ಗೆ",
        "doctorAboutTab": "ಬಗ್ಗೆ",
        "doctorStatics": "ಅಂಕಿಅಂಶಗಳು",
        "doctorCoverPhoto": "ಕವರ್ ಫೋಟೋ",
        "doctorAddCoverPhoto": "ಕವರ್ ಫೋಟೋ ಸೇರಿಸಿ",
        "doctorExpertise": "ಪರಿಣತಿ",
        "doctorExpertiseHint": "ಉದಾ. ಆಂಜಿಯೋಪ್ಲಾಸ್ಟಿ",
        "doctorAddExpertise": "ನಿಮ್ಮ ಪರಿಣತಿಯನ್ನು ಸೇರಿಸಿ",
        "doctorCertificateAwards": "ಪ್ರಮಾಣಪತ್ರಗಳು ಮತ್ತು ಪ್ರಶಸ್ತಿಗಳು",
        "doctorAddCertificate": "ಪ್ರಮಾಣಪತ್ರ ಸೇರಿಸಿ",
        "doctorEditCertificate": "ಪ್ರಮಾಣಪತ್ರ ಸಂಪಾದಿಸಿ",
        "doctorNoCertificates": "ನಿಮ್ಮ ಮೊದಲ ಪ್ರಮಾಣಪತ್ರ ಸೇರಿಸಿ",
        "doctorCertificateImage": "ಪ್ರಮಾಣಪತ್ರ ಚಿತ್ರ",
        "doctorCertificateTitleHint": "ಉದಾ. ಸದಸ್ಯತ್ವ ಪ್ರಮಾಣಪತ್ರ",
        "doctorCertificateDescHint": "ಈ ಪ್ರಮಾಣಪತ್ರವನ್ನು ವಿವರಿಸಿ...",
        "doctorCertificateTitleRequired":
            "ದಯವಿಟ್ಟು ಪ್ರಮಾಣಪತ್ರದ ಶೀರ್ಷಿಕೆಯನ್ನು ನಮೂದಿಸಿ",
        "doctorCertificateTitleLimit":
            "ಶೀರ್ಷಿಕೆ 200 ಅಕ್ಷರಗಳನ್ನು ಮೀರಬಾರದು",
        "doctorIssuedBy": "ವಿತರಿಸಿದವರು",
        "doctorIssuedByHint": "ಉದಾ. ಮೆಡಿಕಲ್ ಕೌನ್ಸಿಲ್ ಆಫ್ ಇಂಡಿಯಾ",
        "doctorIssuedDate": "ವಿತರಣಾ ದಿನಾಂಕ",
        "doctorSelectDate": "ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ",
        "doctorImageTooLarge": "ಚಿತ್ರ 10 MB ಅಥವಾ ಕಡಿಮೆ ಇರಬೇಕು",
        "doctorAddPhoto": "ಫೋಟೋ ಸೇರಿಸಿ",
        "doctorGalleryEmpty":
            "ನಿಮ್ಮ ಗ್ಯಾಲರಿ ಖಾಲಿಯಾಗಿದೆ - ಪ್ರದರ್ಶಿಸಲು ಫೋಟೋಗಳನ್ನು ಸೇರಿಸಿ",
        "doctorDegree": "ಪದವಿ",
        "doctorDegreeHint": "ಉದಾ. ಎಂಬಿಬಿಎಸ್",
        "doctorSpecialization": "ವಿಶೇಷತೆ",
        "doctorSpecializationHint": "ಉದಾ. ಹೃದ್ರೋಗ ತಜ್ಞ",
        "doctorLanguageSpoken": "ಮಾತನಾಡುವ ಭಾಷೆ",
        "doctorLanguageHint": "ಉದಾ. ಇಂಗ್ಲಿಷ್",
        "doctorLanguagesSpoken": "ಮಾತನಾಡುವ ಭಾಷೆಗಳು",
        "doctorExperience": "ಅನುಭವ",
        "doctorExperienceHint": "ಉದಾ. 10 ವರ್ಷಗಳು",
        "doctorYears": "ವರ್ಷಗಳು",
        "doctorRegistrationNumber": "ನೋಂದಣಿ ಸಂಖ್ಯೆ",
        "doctorRegistrationHint": "ಉದಾ. 2345/MC/2015",
        "doctorConsultationFee": "ಸಮಾಲೋಚನೆ ಶುಲ್ಕ",
        "doctorFeeHint": "ಉದಾ. 600",
        "doctorAddressHint": "ಉದಾ. 123 ಪಾರ್ಕ್ ಸ್ಟ್ರೀಟ್, ಕೋಲ್ಕತಾ",
        "doctorDescriptionHint": "ರೋಗಿಗಳಿಗೆ ನಿಮ್ಮ ಬಗ್ಗೆ ತಿಳಿಸಿ...",
        "doctorConsultationAvailability": "ಸಮಾಲೋಚನೆ ಲಭ್ಯತೆ",
        "doctorAddVisitingDays": "ನಿಮ್ಮ ಭೇಟಿ ದಿನಗಳನ್ನು ಸೇರಿಸಿ",
        "doctorCompleteProfileTitle": "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ",
        "doctorCompleteProfileBody":
            "ರೋಗಿಗಳು ನಿಮ್ಮನ್ನು ಹುಡುಕಲು ಮತ್ತು ಬುಕ್ ಮಾಡಲು ನಿಮ್ಮ ಪದವಿ, ವಿಶೇಷತೆ ಮತ್ತು ಶುಲ್ಕವನ್ನು ಸೇರಿಸಿ.",
        "doctorCreateProfile": "ಪ್ರೊಫೈಲ್ ರಚಿಸಿ",
        "doctorMaxEntriesError":
            "ಪ್ರತಿ ಕ್ಷೇತ್ರಕ್ಕೆ ಗರಿಷ್ಠ 30 ನಮೂದುಗಳನ್ನು ಸೇರಿಸಬಹುದು",
        "doctorExperienceRangeError":
            "ಅನುಭವ 0 ರಿಂದ 80 ವರ್ಷಗಳ ನಡುವೆ ಇರಬೇಕು",
        "doctorFeeError": "ಸಮಾಲೋಚನೆ ಶುಲ್ಕ 0 ಅಥವಾ ಹೆಚ್ಚು ಇರಬೇಕು",
        "doctorDescriptionLimitError":
            "ವಿವರಣೆ 1000 ಅಕ್ಷರಗಳನ್ನು ಮೀರಬಾರದು",
        "doctorNoAppointments": "ಇನ್ನೂ ಯಾವುದೇ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ವಿನಂತಿ ಇಲ್ಲ",
        "doctorLoadMore": "ಇನ್ನಷ್ಟು ಲೋಡ್ ಮಾಡಿ",
        "doctorFilterAll": "ಎಲ್ಲಾ",
        "doctorStatusPending": "ಬಾಕಿ",
        "doctorStatusAccepted": "ಸ್ವೀಕರಿಸಲಾಗಿದೆ",
        "doctorStatusDeclined": "ನಿರಾಕರಿಸಲಾಗಿದೆ",
        "doctorStatusCancelled": "ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ",
        "doctorAccept": "ಸ್ವೀಕರಿಸಿ",
        "doctorDecline": "ನಿರಾಕರಿಸಿ",
        "doctorPatient": "ರೋಗಿ",
        "doctorAttachments": "ಲಗತ್ತುಗಳು",
        "doctorAppointmentStats": "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು",
        "doctorTotalRequests": "ಒಟ್ಟು ವಿನಂತಿಗಳು",
        "doctorUpcomingVisits": "ಮುಂಬರುವ ಭೇಟಿಗಳು",
        "doctorCertificates": "ಪ್ರಮಾಣಪತ್ರಗಳು",
        "read_less": "ಕಡಿಮೆ ಓದಿ",
        "retry": "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
    },
}

os.makedirs(OUT_DIR, exist_ok=True)

for lang, entries in T.items():
    path = os.path.join(TRANS_DIR, f"{lang}.json")
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    added = [k for k in entries if k not in data]
    existing = [k for k in data if k not in added]
    data.update(entries)
    if existing == sorted(existing):
        data = {k: data[k] for k in sorted(data)}
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")

    out = os.path.join(OUT_DIR, f"{lang}.json")
    with open(out, "w", encoding="utf-8") as f:
        json.dump(entries, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"{lang}: {len(entries)} keys written ({len(added)} new locally)")
