#!/usr/bin/env python3
"""Add rider_profile_status_screen localization keys to local asset JSONs
(en/hi/gu/kn/mr) and emit per-language PUT payloads for the language API.

Run:  python3 scripts/rider_status_localization.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TRANS_DIR = os.path.join(ROOT, "assets", "translations")
OUT_DIR = os.path.join(ROOT, "scripts", "rider_status_lang_payloads")

T = {
    "en": {
        "applicationSubmittedSuccessfully": "Application Submitted\nSuccessfully!",
        "profileUnderVerificationMsg": "Your profile is under verification. We will notify you once your profile is verified.",
        "whatHappensNext": "What happens next?",
        "documentReview": "Document Review",
        "documentReviewSubtitle": "Our team will verify all your uploaded documents",
        "getNotified": "Get Notified",
        "getNotifiedSubtitle": "You'll receive a notification once approved",
        "startDelivering": "Start Delivering",
        "startDeliveringSubtitle": "Accept orders and start earning",
        "profileVerified": "Profile Verified",
        "allSetToAcceptDeliveries": "You're all set to accept deliveries!",
        "noOrdersYet": "No Orders Yet",
        "noOrdersYetSubtitle": "New delivery requests will appear here.\nStay online to receive orders nearby.",
        "tipsToGetMoreOrders": "Tips to Get More Orders",
        "tipStayHighDemand": "Stay in high-demand areas for faster pickups",
        "tipPeakHours": "Peak hours: 11 AM - 2 PM & 6 PM - 10 PM",
        "tipMaintainRatings": "Maintain good ratings to get priority orders",
        "tipStableInternet": "Keep your internet connection stable",
        "verificationRejectedMsg": "Your verification was rejected. Please review and re-upload the required documents.",
        "joinedLabel": "Joined",
        "submitForVerification": "Submit for Verification",
        "submitApplicationQuestion": "Submit Application?",
        "submitApplicationConfirmMsg": "Please make sure all your documents are correct. Once submitted, your application will be reviewed by our team.",
        "chooseYourRideType": "Choose Your Ride Type",
        "selectHowToServe": "Select how you'd like to serve on BlueEra",
        "passengerRider": "Passenger Rider",
        "passengerRiderSubtitle": "Pick up & drop off passengers",
        "deliveryRider": "Delivery Rider",
        "deliveryRiderSubtitle": "Deliver food, parcels & groceries",
        "bothRideType": "Both",
        "bothRiderSubtitle": "Passenger rides & deliveries",
        "preferenceSaved": "Preference saved! You can change this later.",
        "needHelpQuestion": "Need Help?",
        "contactUsForQueries": "Contact us for any queries or support",
        "describeYourQuery": "Describe your query",
        "queryHintText": "Type your question or concern here...",
        "pleaseDescribeQuery": "Please describe your query",
        "submitQuery": "Submit Query",
        "querySubmitted": "Query Submitted!",
        "querySubmittedMsg": "Thank you for reaching out. Our support team will get back to you shortly.",
        "categoryGeneral": "General",
        "categoryDocumentIssue": "Document Issue",
        "categoryVerificationDelay": "Verification Delay",
        "categoryTechnicalIssue": "Technical Issue",
        "categoryOther": "Other",
        "addYourVehicleInfo": "Add Your Vehicle Info",
        "egVehicleNo": "E.g. WB40 5566",
        "addYourAadharNumber": "Add Your Aadhar Number",
        "egAadharNo": "E.g. 1233 1236 1233",
        "addYourPanNumber": "Add Your Pan Number",
        "egPanNo": "E.g. ABCDE1234F",
        "addYourDrivingLicenceNumber": "Add Your Driving Licence Number",
        "egDlNo": "E.g. DL01201110012345",
        "addYourRcNumber": "Add Your RC Number",
        "egRcNo": "E.g. WB12kmxl",
        "rcBook": "RC Book",
        "uploadVehicleImage": "Upload Vehicle Image",
        "documentReceived": "Document received",
        "viewDocument": "View Document",
        "addNowCta": "Add Now",
        "couldNotLoadImage": "Could not load image",
        "pinchToZoom": "Pinch to zoom",
        "replaceLabel": "Replace",
    },
    "hi": {
        "applicationSubmittedSuccessfully": "आवेदन सफलतापूर्वक\nजमा किया गया!",
        "profileUnderVerificationMsg": "आपकी प्रोफ़ाइल सत्यापन के अधीन है। प्रोफ़ाइल सत्यापित होने पर हम आपको सूचित करेंगे।",
        "whatHappensNext": "आगे क्या होगा?",
        "documentReview": "दस्तावेज़ समीक्षा",
        "documentReviewSubtitle": "हमारी टीम आपके सभी अपलोड किए गए दस्तावेज़ों की पुष्टि करेगी",
        "getNotified": "सूचना प्राप्त करें",
        "getNotifiedSubtitle": "स्वीकृत होने पर आपको एक सूचना मिलेगी",
        "startDelivering": "डिलीवरी शुरू करें",
        "startDeliveringSubtitle": "ऑर्डर स्वीकार करें और कमाई शुरू करें",
        "profileVerified": "प्रोफ़ाइल सत्यापित",
        "allSetToAcceptDeliveries": "आप डिलीवरी स्वीकार करने के लिए तैयार हैं!",
        "noOrdersYet": "अभी तक कोई ऑर्डर नहीं",
        "noOrdersYetSubtitle": "नई डिलीवरी अनुरोध यहाँ दिखाई देंगे।\nपास के ऑर्डर पाने के लिए ऑनलाइन रहें।",
        "tipsToGetMoreOrders": "अधिक ऑर्डर पाने के लिए सुझाव",
        "tipStayHighDemand": "तेज़ पिकअप के लिए अधिक मांग वाले क्षेत्रों में रहें",
        "tipPeakHours": "व्यस्त समय: सुबह 11 - दोपहर 2 बजे और शाम 6 - रात 10 बजे",
        "tipMaintainRatings": "प्राथमिकता वाले ऑर्डर पाने के लिए अच्छी रेटिंग बनाए रखें",
        "tipStableInternet": "अपना इंटरनेट कनेक्शन स्थिर रखें",
        "verificationRejectedMsg": "आपका सत्यापन अस्वीकार कर दिया गया। कृपया समीक्षा करें और आवश्यक दस्तावेज़ फिर से अपलोड करें।",
        "joinedLabel": "शामिल हुए",
        "submitForVerification": "सत्यापन के लिए जमा करें",
        "submitApplicationQuestion": "आवेदन जमा करें?",
        "submitApplicationConfirmMsg": "कृपया सुनिश्चित करें कि आपके सभी दस्तावेज़ सही हैं। एक बार जमा करने के बाद, आपके आवेदन की हमारी टीम द्वारा समीक्षा की जाएगी।",
        "chooseYourRideType": "अपना राइड प्रकार चुनें",
        "selectHowToServe": "चुनें कि आप BlueEra पर कैसे सेवा देना चाहते हैं",
        "passengerRider": "यात्री राइडर",
        "passengerRiderSubtitle": "यात्रियों को पिकअप और ड्रॉप करें",
        "deliveryRider": "डिलीवरी राइडर",
        "deliveryRiderSubtitle": "भोजन, पार्सल और किराना सामान पहुँचाएं",
        "bothRideType": "दोनों",
        "bothRiderSubtitle": "यात्री राइड और डिलीवरी",
        "preferenceSaved": "प्राथमिकता सहेजी गई! आप इसे बाद में बदल सकते हैं।",
        "needHelpQuestion": "मदद चाहिए?",
        "contactUsForQueries": "किसी भी प्रश्न या सहायता के लिए हमसे संपर्क करें",
        "describeYourQuery": "अपना प्रश्न बताएं",
        "queryHintText": "अपना प्रश्न या चिंता यहाँ लिखें...",
        "pleaseDescribeQuery": "कृपया अपना प्रश्न बताएं",
        "submitQuery": "प्रश्न जमा करें",
        "querySubmitted": "प्रश्न जमा हो गया!",
        "querySubmittedMsg": "संपर्क करने के लिए धन्यवाद। हमारी सहायता टीम जल्द ही आपसे संपर्क करेगी।",
        "categoryGeneral": "सामान्य",
        "categoryDocumentIssue": "दस्तावेज़ समस्या",
        "categoryVerificationDelay": "सत्यापन में देरी",
        "categoryTechnicalIssue": "तकनीकी समस्या",
        "categoryOther": "अन्य",
        "addYourVehicleInfo": "अपनी वाहन जानकारी जोड़ें",
        "egVehicleNo": "उदा. WB40 5566",
        "addYourAadharNumber": "अपना आधार नंबर जोड़ें",
        "egAadharNo": "उदा. 1233 1236 1233",
        "addYourPanNumber": "अपना पैन नंबर जोड़ें",
        "egPanNo": "उदा. ABCDE1234F",
        "addYourDrivingLicenceNumber": "अपना ड्राइविंग लाइसेंस नंबर जोड़ें",
        "egDlNo": "उदा. DL01201110012345",
        "addYourRcNumber": "अपना आरसी नंबर जोड़ें",
        "egRcNo": "उदा. WB12kmxl",
        "rcBook": "आरसी बुक",
        "uploadVehicleImage": "वाहन छवि अपलोड करें",
        "documentReceived": "दस्तावेज़ प्राप्त हुआ",
        "viewDocument": "दस्तावेज़ देखें",
        "addNowCta": "अभी जोड़ें",
        "couldNotLoadImage": "छवि लोड नहीं हो सकी",
        "pinchToZoom": "ज़ूम करने के लिए पिंच करें",
        "replaceLabel": "बदलें",
    },
    "gu": {
        "applicationSubmittedSuccessfully": "અરજી સફળતાપૂર્વક\nસબમિટ થઈ!",
        "profileUnderVerificationMsg": "તમારી પ્રોફાઇલ ચકાસણી હેઠળ છે. પ્રોફાઇલ ચકાસાઈ જતાં અમે તમને જાણ કરીશું.",
        "whatHappensNext": "હવે શું થશે?",
        "documentReview": "દસ્તાવેજ સમીક્ષા",
        "documentReviewSubtitle": "અમારી ટીમ તમારા બધા અપલોડ કરેલા દસ્તાવેજો ચકાસશે",
        "getNotified": "સૂચના મેળવો",
        "getNotifiedSubtitle": "મંજૂર થયા પછી તમને સૂચના મળશે",
        "startDelivering": "ડિલિવરી શરૂ કરો",
        "startDeliveringSubtitle": "ઓર્ડર સ્વીકારો અને કમાણી શરૂ કરો",
        "profileVerified": "પ્રોફાઇલ ચકાસાઈ",
        "allSetToAcceptDeliveries": "તમે ડિલિવરી સ્વીકારવા માટે તૈયાર છો!",
        "noOrdersYet": "હજી સુધી કોઈ ઓર્ડર નથી",
        "noOrdersYetSubtitle": "નવી ડિલિવરી વિનંતીઓ અહીં દેખાશે.\nનજીકના ઓર્ડર મેળવવા ઓનલાઇન રહો.",
        "tipsToGetMoreOrders": "વધુ ઓર્ડર મેળવવા માટેની ટિપ્સ",
        "tipStayHighDemand": "ઝડપી પિકઅપ માટે વધુ માંગવાળા વિસ્તારોમાં રહો",
        "tipPeakHours": "વ્યસ્ત સમય: સવારે 11 - બપોરે 2 અને સાંજે 6 - રાત્રે 10",
        "tipMaintainRatings": "પ્રાથમિકતા ઓર્ડર મેળવવા સારી રેટિંગ જાળવો",
        "tipStableInternet": "તમારું ઇન્ટરનેટ કનેક્શન સ્થિર રાખો",
        "verificationRejectedMsg": "તમારી ચકાસણી નકારી કાઢવામાં આવી. કૃપા કરીને સમીક્ષા કરો અને જરૂરી દસ્તાવેજો ફરીથી અપલોડ કરો.",
        "joinedLabel": "જોડાયા",
        "submitForVerification": "ચકાસણી માટે સબમિટ કરો",
        "submitApplicationQuestion": "અરજી સબમિટ કરવી છે?",
        "submitApplicationConfirmMsg": "કૃપા કરીને ખાતરી કરો કે તમારા બધા દસ્તાવેજો સાચા છે. એકવાર સબમિટ થયા પછી, તમારી અરજીની અમારી ટીમ દ્વારા સમીક્ષા કરવામાં આવશે.",
        "chooseYourRideType": "તમારો રાઇડ પ્રકાર પસંદ કરો",
        "selectHowToServe": "BlueEra પર તમે કેવી રીતે સેવા આપવા માગો છો તે પસંદ કરો",
        "passengerRider": "પેસેન્જર રાઇડર",
        "passengerRiderSubtitle": "મુસાફરોને પિકઅપ અને ડ્રોપ કરો",
        "deliveryRider": "ડિલિવરી રાઇડર",
        "deliveryRiderSubtitle": "ખોરાક, પાર્સલ અને કરિયાણા પહોંચાડો",
        "bothRideType": "બંને",
        "bothRiderSubtitle": "પેસેન્જર રાઇડ અને ડિલિવરી",
        "preferenceSaved": "પસંદગી સાચવાઈ! તમે આને પછીથી બદલી શકો છો.",
        "needHelpQuestion": "મદદ જોઈએ છે?",
        "contactUsForQueries": "કોઈપણ પ્રશ્નો અથવા સહાય માટે અમારો સંપર્ક કરો",
        "describeYourQuery": "તમારો પ્રશ્ન વર્ણવો",
        "queryHintText": "તમારો પ્રશ્ન અથવા ચિંતા અહીં લખો...",
        "pleaseDescribeQuery": "કૃપા કરીને તમારો પ્રશ્ન વર્ણવો",
        "submitQuery": "પ્રશ્ન સબમિટ કરો",
        "querySubmitted": "પ્રશ્ન સબમિટ થયો!",
        "querySubmittedMsg": "સંપર્ક કરવા બદલ આભાર. અમારી સહાય ટીમ ટૂંક સમયમાં તમારો સંપર્ક કરશે.",
        "categoryGeneral": "સામાન્ય",
        "categoryDocumentIssue": "દસ્તાવેજ સમસ્યા",
        "categoryVerificationDelay": "ચકાસણીમાં વિલંબ",
        "categoryTechnicalIssue": "ટેકનિકલ સમસ્યા",
        "categoryOther": "અન્ય",
        "addYourVehicleInfo": "તમારી વાહન માહિતી ઉમેરો",
        "egVehicleNo": "દા.ત. WB40 5566",
        "addYourAadharNumber": "તમારો આધાર નંબર ઉમેરો",
        "egAadharNo": "દા.ત. 1233 1236 1233",
        "addYourPanNumber": "તમારો પાન નંબર ઉમેરો",
        "egPanNo": "દા.ત. ABCDE1234F",
        "addYourDrivingLicenceNumber": "તમારો ડ્રાઇવિંગ લાઇસન્સ નંબર ઉમેરો",
        "egDlNo": "દા.ત. DL01201110012345",
        "addYourRcNumber": "તમારો આરસી નંબર ઉમેરો",
        "egRcNo": "દા.ત. WB12kmxl",
        "rcBook": "આરસી બુક",
        "uploadVehicleImage": "વાહન છબી અપલોડ કરો",
        "documentReceived": "દસ્તાવેજ પ્રાપ્ત થયો",
        "viewDocument": "દસ્તાવેજ જુઓ",
        "addNowCta": "હમણાં ઉમેરો",
        "couldNotLoadImage": "છબી લોડ થઈ શકી નથી",
        "pinchToZoom": "ઝૂમ કરવા પિંચ કરો",
        "replaceLabel": "બદલો",
    },
    "mr": {
        "applicationSubmittedSuccessfully": "अर्ज यशस्वीरित्या\nसबमिट झाला!",
        "profileUnderVerificationMsg": "तुमची प्रोफाइल पडताळणीखाली आहे. प्रोफाइल पडताळल्यावर आम्ही तुम्हाला सूचित करू.",
        "whatHappensNext": "पुढे काय होईल?",
        "documentReview": "कागदपत्र पुनरावलोकन",
        "documentReviewSubtitle": "आमची टीम तुमच्या सर्व अपलोड केलेल्या कागदपत्रांची पडताळणी करेल",
        "getNotified": "सूचना मिळवा",
        "getNotifiedSubtitle": "मंजूर झाल्यावर तुम्हाला सूचना मिळेल",
        "startDelivering": "डिलिव्हरी सुरू करा",
        "startDeliveringSubtitle": "ऑर्डर स्वीकारा आणि कमाई सुरू करा",
        "profileVerified": "प्रोफाइल पडताळली",
        "allSetToAcceptDeliveries": "तुम्ही डिलिव्हरी स्वीकारण्यासाठी तयार आहात!",
        "noOrdersYet": "अद्याप कोणतेही ऑर्डर नाहीत",
        "noOrdersYetSubtitle": "नवीन डिलिव्हरी विनंत्या येथे दिसतील.\nजवळचे ऑर्डर मिळवण्यासाठी ऑनलाइन रहा.",
        "tipsToGetMoreOrders": "अधिक ऑर्डर मिळवण्यासाठी टिप्स",
        "tipStayHighDemand": "जलद पिकअपसाठी जास्त मागणी असलेल्या भागात रहा",
        "tipPeakHours": "गर्दीचा वेळ: सकाळी 11 - दुपारी 2 आणि संध्याकाळी 6 - रात्री 10",
        "tipMaintainRatings": "प्राधान्य ऑर्डर मिळवण्यासाठी चांगले रेटिंग ठेवा",
        "tipStableInternet": "तुमचे इंटरनेट कनेक्शन स्थिर ठेवा",
        "verificationRejectedMsg": "तुमची पडताळणी नाकारली गेली. कृपया पुनरावलोकन करा आणि आवश्यक कागदपत्रे पुन्हा अपलोड करा.",
        "joinedLabel": "सामील झाले",
        "submitForVerification": "पडताळणीसाठी सबमिट करा",
        "submitApplicationQuestion": "अर्ज सबमिट करायचा?",
        "submitApplicationConfirmMsg": "कृपया खात्री करा की तुमची सर्व कागदपत्रे बरोबर आहेत. एकदा सबमिट केल्यावर, तुमच्या अर्जाचे आमच्या टीमकडून पुनरावलोकन केले जाईल.",
        "chooseYourRideType": "तुमचा राइड प्रकार निवडा",
        "selectHowToServe": "BlueEra वर तुम्हाला कशी सेवा द्यायची आहे ते निवडा",
        "passengerRider": "प्रवासी राइडर",
        "passengerRiderSubtitle": "प्रवाशांना पिकअप आणि ड्रॉप करा",
        "deliveryRider": "डिलिव्हरी राइडर",
        "deliveryRiderSubtitle": "अन्न, पार्सल आणि किराणा पोहोचवा",
        "bothRideType": "दोन्ही",
        "bothRiderSubtitle": "प्रवासी राइड आणि डिलिव्हरी",
        "preferenceSaved": "प्राधान्य जतन केले! तुम्ही हे नंतर बदलू शकता.",
        "needHelpQuestion": "मदत हवी आहे?",
        "contactUsForQueries": "कोणत्याही प्रश्नांसाठी किंवा मदतीसाठी आमच्याशी संपर्क साधा",
        "describeYourQuery": "तुमचा प्रश्न वर्णन करा",
        "queryHintText": "तुमचा प्रश्न किंवा चिंता येथे लिहा...",
        "pleaseDescribeQuery": "कृपया तुमचा प्रश्न वर्णन करा",
        "submitQuery": "प्रश्न सबमिट करा",
        "querySubmitted": "प्रश्न सबमिट झाला!",
        "querySubmittedMsg": "संपर्क केल्याबद्दल धन्यवाद. आमची सहाय्यता टीम लवकरच तुमच्याशी संपर्क साधेल.",
        "categoryGeneral": "सामान्य",
        "categoryDocumentIssue": "कागदपत्र समस्या",
        "categoryVerificationDelay": "पडताळणीत विलंब",
        "categoryTechnicalIssue": "तांत्रिक समस्या",
        "categoryOther": "इतर",
        "addYourVehicleInfo": "तुमची वाहन माहिती जोडा",
        "egVehicleNo": "उदा. WB40 5566",
        "addYourAadharNumber": "तुमचा आधार क्रमांक जोडा",
        "egAadharNo": "उदा. 1233 1236 1233",
        "addYourPanNumber": "तुमचा पॅन क्रमांक जोडा",
        "egPanNo": "उदा. ABCDE1234F",
        "addYourDrivingLicenceNumber": "तुमचा ड्रायव्हिंग लायसन्स क्रमांक जोडा",
        "egDlNo": "उदा. DL01201110012345",
        "addYourRcNumber": "तुमचा आरसी क्रमांक जोडा",
        "egRcNo": "उदा. WB12kmxl",
        "rcBook": "आरसी बुक",
        "uploadVehicleImage": "वाहन प्रतिमा अपलोड करा",
        "documentReceived": "कागदपत्र प्राप्त झाले",
        "viewDocument": "कागदपत्र पहा",
        "addNowCta": "आता जोडा",
        "couldNotLoadImage": "प्रतिमा लोड होऊ शकली नाही",
        "pinchToZoom": "झूम करण्यासाठी पिंच करा",
        "replaceLabel": "बदला",
    },
    "kn": {
        "applicationSubmittedSuccessfully": "ಅರ್ಜಿ ಯಶಸ್ವಿಯಾಗಿ\nಸಲ್ಲಿಸಲಾಗಿದೆ!",
        "profileUnderVerificationMsg": "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ. ಪ್ರೊಫೈಲ್ ಪರಿಶೀಲಿಸಿದ ನಂತರ ನಾವು ನಿಮಗೆ ತಿಳಿಸುತ್ತೇವೆ.",
        "whatHappensNext": "ಮುಂದೆ ಏನಾಗುತ್ತದೆ?",
        "documentReview": "ದಾಖಲೆ ಪರಿಶೀಲನೆ",
        "documentReviewSubtitle": "ನಮ್ಮ ತಂಡ ನಿಮ್ಮ ಎಲ್ಲಾ ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ದಾಖಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸುತ್ತದೆ",
        "getNotified": "ಅಧಿಸೂಚನೆ ಪಡೆಯಿರಿ",
        "getNotifiedSubtitle": "ಅನುಮೋದಿಸಿದ ನಂತರ ನಿಮಗೆ ಅಧಿಸೂಚನೆ ಸಿಗುತ್ತದೆ",
        "startDelivering": "ಡೆಲಿವರಿ ಪ್ರಾರಂಭಿಸಿ",
        "startDeliveringSubtitle": "ಆರ್ಡರ್‌ಗಳನ್ನು ಸ್ವೀಕರಿಸಿ ಮತ್ತು ಗಳಿಕೆ ಪ್ರಾರಂಭಿಸಿ",
        "profileVerified": "ಪ್ರೊಫೈಲ್ ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
        "allSetToAcceptDeliveries": "ನೀವು ಡೆಲಿವರಿಗಳನ್ನು ಸ್ವೀಕರಿಸಲು ಸಿದ್ಧರಿದ್ದೀರಿ!",
        "noOrdersYet": "ಇನ್ನೂ ಯಾವುದೇ ಆರ್ಡರ್‌ಗಳಿಲ್ಲ",
        "noOrdersYetSubtitle": "ಹೊಸ ಡೆಲಿವರಿ ವಿನಂತಿಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.\nಹತ್ತಿರದ ಆರ್ಡರ್‌ಗಳನ್ನು ಪಡೆಯಲು ಆನ್‌ಲೈನ್‌ನಲ್ಲಿರಿ.",
        "tipsToGetMoreOrders": "ಹೆಚ್ಚು ಆರ್ಡರ್‌ಗಳನ್ನು ಪಡೆಯಲು ಸಲಹೆಗಳು",
        "tipStayHighDemand": "ವೇಗದ ಪಿಕಪ್‌ಗಾಗಿ ಹೆಚ್ಚು ಬೇಡಿಕೆಯ ಪ್ರದೇಶಗಳಲ್ಲಿರಿ",
        "tipPeakHours": "ಗರಿಷ್ಠ ಸಮಯ: ಬೆಳಿಗ್ಗೆ 11 - ಮಧ್ಯಾಹ್ನ 2 ಮತ್ತು ಸಂಜೆ 6 - ರಾತ್ರಿ 10",
        "tipMaintainRatings": "ಆದ್ಯತೆ ಆರ್ಡರ್‌ಗಳನ್ನು ಪಡೆಯಲು ಉತ್ತಮ ರೇಟಿಂಗ್ ನಿರ್ವಹಿಸಿ",
        "tipStableInternet": "ನಿಮ್ಮ ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕವನ್ನು ಸ್ಥಿರವಾಗಿ ಇರಿಸಿ",
        "verificationRejectedMsg": "ನಿಮ್ಮ ಪರಿಶೀಲನೆಯನ್ನು ತಿರಸ್ಕರಿಸಲಾಗಿದೆ. ದಯವಿಟ್ಟು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಅಗತ್ಯವಿರುವ ದಾಖಲೆಗಳನ್ನು ಮರು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
        "joinedLabel": "ಸೇರಿದರು",
        "submitForVerification": "ಪರಿಶೀಲನೆಗಾಗಿ ಸಲ್ಲಿಸಿ",
        "submitApplicationQuestion": "ಅರ್ಜಿ ಸಲ್ಲಿಸುವುದೇ?",
        "submitApplicationConfirmMsg": "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಎಲ್ಲಾ ದಾಖಲೆಗಳು ಸರಿಯಾಗಿವೆ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ. ಒಮ್ಮೆ ಸಲ್ಲಿಸಿದ ನಂತರ, ನಿಮ್ಮ ಅರ್ಜಿಯನ್ನು ನಮ್ಮ ತಂಡ ಪರಿಶೀಲಿಸುತ್ತದೆ.",
        "chooseYourRideType": "ನಿಮ್ಮ ರೈಡ್ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
        "selectHowToServe": "BlueEra ನಲ್ಲಿ ನೀವು ಹೇಗೆ ಸೇವೆ ಸಲ್ಲಿಸಲು ಬಯಸುತ್ತೀರಿ ಎಂಬುದನ್ನು ಆಯ್ಕೆಮಾಡಿ",
        "passengerRider": "ಪ್ರಯಾಣಿಕ ರೈಡರ್",
        "passengerRiderSubtitle": "ಪ್ರಯಾಣಿಕರನ್ನು ಪಿಕಪ್ ಮತ್ತು ಡ್ರಾಪ್ ಮಾಡಿ",
        "deliveryRider": "ಡೆಲಿವರಿ ರೈಡರ್",
        "deliveryRiderSubtitle": "ಆಹಾರ, ಪಾರ್ಸೆಲ್‌ಗಳು ಮತ್ತು ದಿನಸಿ ತಲುಪಿಸಿ",
        "bothRideType": "ಎರಡೂ",
        "bothRiderSubtitle": "ಪ್ರಯಾಣಿಕ ರೈಡ್ ಮತ್ತು ಡೆಲಿವರಿ",
        "preferenceSaved": "ಆದ್ಯತೆ ಉಳಿಸಲಾಗಿದೆ! ನೀವು ಇದನ್ನು ನಂತರ ಬದಲಾಯಿಸಬಹುದು.",
        "needHelpQuestion": "ಸಹಾಯ ಬೇಕೇ?",
        "contactUsForQueries": "ಯಾವುದೇ ಪ್ರಶ್ನೆಗಳು ಅಥವಾ ಬೆಂಬಲಕ್ಕಾಗಿ ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ",
        "describeYourQuery": "ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ವಿವರಿಸಿ",
        "queryHintText": "ನಿಮ್ಮ ಪ್ರಶ್ನೆ ಅಥವಾ ಕಾಳಜಿಯನ್ನು ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ...",
        "pleaseDescribeQuery": "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ವಿವರಿಸಿ",
        "submitQuery": "ಪ್ರಶ್ನೆ ಸಲ್ಲಿಸಿ",
        "querySubmitted": "ಪ್ರಶ್ನೆ ಸಲ್ಲಿಸಲಾಗಿದೆ!",
        "querySubmittedMsg": "ಸಂಪರ್ಕಿಸಿದ್ದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು. ನಮ್ಮ ಬೆಂಬಲ ತಂಡ ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತದೆ.",
        "categoryGeneral": "ಸಾಮಾನ್ಯ",
        "categoryDocumentIssue": "ದಾಖಲೆ ಸಮಸ್ಯೆ",
        "categoryVerificationDelay": "ಪರಿಶೀಲನೆ ವಿಳಂಬ",
        "categoryTechnicalIssue": "ತಾಂತ್ರಿಕ ಸಮಸ್ಯೆ",
        "categoryOther": "ಇತರೆ",
        "addYourVehicleInfo": "ನಿಮ್ಮ ವಾಹನ ಮಾಹಿತಿಯನ್ನು ಸೇರಿಸಿ",
        "egVehicleNo": "ಉದಾ. WB40 5566",
        "addYourAadharNumber": "ನಿಮ್ಮ ಆಧಾರ್ ಸಂಖ್ಯೆಯನ್ನು ಸೇರಿಸಿ",
        "egAadharNo": "ಉದಾ. 1233 1236 1233",
        "addYourPanNumber": "ನಿಮ್ಮ ಪ್ಯಾನ್ ಸಂಖ್ಯೆಯನ್ನು ಸೇರಿಸಿ",
        "egPanNo": "ಉದಾ. ABCDE1234F",
        "addYourDrivingLicenceNumber": "ನಿಮ್ಮ ಚಾಲನಾ ಪರವಾನಗಿ ಸಂಖ್ಯೆಯನ್ನು ಸೇರಿಸಿ",
        "egDlNo": "ಉದಾ. DL01201110012345",
        "addYourRcNumber": "ನಿಮ್ಮ ಆರ್‌ಸಿ ಸಂಖ್ಯೆಯನ್ನು ಸೇರಿಸಿ",
        "egRcNo": "ಉದಾ. WB12kmxl",
        "rcBook": "ಆರ್‌ಸಿ ಬುಕ್",
        "uploadVehicleImage": "ವಾಹನ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
        "documentReceived": "ದಾಖಲೆ ಸ್ವೀಕರಿಸಲಾಗಿದೆ",
        "viewDocument": "ದಾಖಲೆ ವೀಕ್ಷಿಸಿ",
        "addNowCta": "ಈಗ ಸೇರಿಸಿ",
        "couldNotLoadImage": "ಚಿತ್ರವನ್ನು ಲೋಡ್ ಮಾಡಲಾಗಲಿಲ್ಲ",
        "pinchToZoom": "ಜೂಮ್ ಮಾಡಲು ಪಿಂಚ್ ಮಾಡಿ",
        "replaceLabel": "ಬದಲಾಯಿಸಿ",
    },
}

BASE_URL = "https://be.beapp.in/api/language-service/languages"


def update_assets():
    for lang, kv in T.items():
        path = os.path.join(TRANS_DIR, f"{lang}.json")
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        added = sum(1 for k in kv if k not in data)
        data.update(kv)
        data = dict(sorted(data.items(), key=lambda x: x[0]))
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
            f.write("\n")
        print(f"{lang}.json: +{added} new keys (merged {len(kv)})")


def emit_payloads():
    os.makedirs(OUT_DIR, exist_ok=True)
    lines = []
    for lang, kv in T.items():
        body = json.dumps(kv, ensure_ascii=False, indent=2)
        with open(os.path.join(OUT_DIR, f"{lang}.json"), "w", encoding="utf-8") as f:
            f.write(body + "\n")
        lines.append(f"curl -X 'PUT' \\\n"
                     f"  '{BASE_URL}/{lang}' \\\n"
                     f"  -H 'accept: */*' \\\n"
                     f"  -H 'Content-Type: application/json' \\\n"
                     f"  -d @scripts/rider_status_lang_payloads/{lang}.json\n")
    with open(os.path.join(OUT_DIR, "curl_commands.sh"), "w", encoding="utf-8") as f:
        f.write("#!/usr/bin/env bash\nset -e\n\n" + "\n".join(lines))
    print(f"payloads + curl_commands.sh written to {OUT_DIR}")


if __name__ == "__main__":
    update_assets()
    emit_payloads()
